### ISSUE TITLE
Set the website of this GitHub repo to the demo

### ISSUE THREAD

**Issue by dandv** [shshaw/SVGvsFont#1]
http://shshaw.github.io/SVGvsFont

Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

Enjoyed the comparison, BTW. Thanks!

**Comment by shshaw** [comment]
Ah! I was unaware of that option. I've plugged it in now. Thanks for the tip.
